//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsDEV
{
    using System;
    using System.Collections.Generic;
    
    public partial class WWWStatistiche
    {
        public string wwsId { get; set; }
        public string wwsUserId { get; set; }
        public int wwsCntAccessi { get; set; }
        public int wwsCntIntArticoli { get; set; }
        public int wwsCntEstrazioni { get; set; }
        public System.DateTime wwsUltimoAccesso { get; set; }
        public byte[] ts { get; set; }
    }
}
